version: "3.3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "npm run start -- --host=0.0.0.0 --disable-host-check"
    ports:
      - "4200:4200"
    container_name: edlinker-front-end
    volumes:
      - .:/app

  mock-json:
    image: 'ajoelpod/mock-json-server'
    volumes:
      - ./api/db.json:/usr/src/app/data.json
    ports:
      - 8000:8000
