version: "3.3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "npm run start -- --host=0.0.0.0 --disable-host-check"
    ports:
      - "4200:4200"
    container_name: edlinker-front-end
    volumes:
      - .:/app