version: "3.3"
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    container_name: edlinker-front-end
    volumes:
      - .:/home/dev/edlinker/edliker-front
    