# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ production_heroku ]
  pull_request:
    branches: [ production_heroku ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Heroku Container registry
        run: heroku container:login

      - name: Build and push
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web

      - name: Release
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
